-- Create release_schedule table
CREATE TABLE IF NOT EXISTS public.release_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_name TEXT NOT NULL UNIQUE, -- e.g. "2025.11"
    launch_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.release_schedule ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Allow read access to authenticated users" ON public.release_schedule;
CREATE POLICY "Allow read access to authenticated users" ON public.release_schedule
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow write access to authenticated users" ON public.release_schedule;
CREATE POLICY "Allow write access to authenticated users" ON public.release_schedule
    FOR ALL TO authenticated USING (true);
