-- Fix release_schedule table naming if it has spaces
-- This migration ensures the table and column names use underscores, not spaces

-- Rename table if it exists with spaces
DO $$
BEGIN
    -- Check if table with spaces exists and rename it
    IF EXISTS (
        SELECT 1 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_name = 'release schedule'
    ) THEN
        -- Rename the table
        ALTER TABLE IF EXISTS "release schedule" RENAME TO release_schedule;
    END IF;
END $$;

-- Rename column if it exists with spaces
DO $$
BEGIN
    -- Check if column with spaces exists and rename it
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'release_schedule'
        AND column_name = 'launch date'
    ) THEN
        -- Rename the column
        ALTER TABLE release_schedule RENAME COLUMN "launch date" TO launch_date;
    END IF;
END $$;

-- Ensure the table exists with correct naming (idempotent)
CREATE TABLE IF NOT EXISTS public.release_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_name TEXT NOT NULL UNIQUE,
    launch_date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure RLS is enabled
ALTER TABLE public.release_schedule ENABLE ROW LEVEL SECURITY;

-- Recreate policies if they don't exist
DROP POLICY IF EXISTS "Allow read access to authenticated users" ON public.release_schedule;
CREATE POLICY "Allow read access to authenticated users" ON public.release_schedule
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow write access to authenticated users" ON public.release_schedule;
CREATE POLICY "Allow write access to authenticated users" ON public.release_schedule
    FOR ALL TO authenticated USING (true);




