-- Create launch_stages table
CREATE TABLE IF NOT EXISTS public.launch_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    sort_order INTEGER NOT NULL UNIQUE,
    duration_days INTEGER, -- NULL means N/A or ongoing
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.launch_stages ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Allow read access to authenticated users" ON public.launch_stages;
CREATE POLICY "Allow read access to authenticated users" ON public.launch_stages
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow write access to authenticated users" ON public.launch_stages;
CREATE POLICY "Allow write access to authenticated users" ON public.launch_stages
    FOR ALL TO authenticated USING (true);

-- Insert initial data
INSERT INTO public.launch_stages (name, sort_order, duration_days, details) VALUES
    ('GTM Access', 1, 14, E'Features available and functioning properly\n\nWe start testing and building all product education and most enablement content\n\nASK Ideally, RnD documentation is ready on this date\n\nASK Product Managers are available to answer our questions in a timely manner\n\nASK Go/No Go typically happens here about 1 week in'),
    ('Internal Readiness', 2, 21, E'Product Education documentation and training is ready for internal teams to consume.\n\nInternal teams upskill on the feature.\n\nDuring this time internal enablement teams will continue to build team-specific materials, refine customer comms, and customer facing materials.'),
    ('Cohort 1 Live', 3, 28, E'First batch of customers are live with the new feature and we are ready to support them.\n\nCustomer facing training/pendo''s/help center articles complete.\n\nService Delivery and Support processes trained in and ready to execute.'),
    ('GA / Cohort 2 Live', 4, NULL, 'All customers are live with the new feature')
ON CONFLICT (sort_order) DO NOTHING;

