-- Add scope, level_durations, and is_gate to launch_stages for UI Rollout stage sets.
-- scope: 'release_schedule' (legacy) | 'ui_rollout'
-- level_durations: JSONB for UI Rollout stages only, e.g. {"1": {"min_days": 42, "max_days": 56}, ...}
-- is_gate: marks stage boundary as a Go/No-Go checkpoint
--
-- Works against public.launch_stages OR public.release_stages (if migration 20260314000000 ran first).
-- Bootstraps launch_stages when neither exists (empty DB missing 20251202000000_create_launch_stages.sql).

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name IN ('launch_stages', 'release_stages')
  ) THEN
    CREATE TABLE public.launch_stages (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      sort_order INTEGER NOT NULL,
      duration_days INTEGER,
      details TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    );
    ALTER TABLE public.launch_stages ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Allow read access to authenticated users" ON public.launch_stages;
    CREATE POLICY "Allow read access to authenticated users" ON public.launch_stages
      FOR SELECT TO authenticated USING (true);
    DROP POLICY IF EXISTS "Allow write access to authenticated users" ON public.launch_stages;
    CREATE POLICY "Allow write access to authenticated users" ON public.launch_stages
      FOR ALL TO authenticated USING (true);
    INSERT INTO public.launch_stages (name, sort_order, duration_days, details)
    SELECT 'GTM Access', 1, 14, E'Features available and functioning properly\n\nWe start testing and building all product education and most enablement content\n\nASK Ideally, RnD documentation is ready on this date\n\nASK Product Managers are available to answer our questions in a timely manner\n\nASK Go/No Go typically happens here about 1 week in'
    WHERE NOT EXISTS (SELECT 1 FROM public.launch_stages WHERE sort_order = 1);
    INSERT INTO public.launch_stages (name, sort_order, duration_days, details)
    SELECT 'Internal Readiness', 2, 21, E'Product Education documentation and training is ready for internal teams to consume.\n\nInternal teams upskill on the feature.\n\nDuring this time internal enablement teams will continue to build team-specific materials, refine customer comms, and customer facing materials.'
    WHERE NOT EXISTS (SELECT 1 FROM public.launch_stages WHERE sort_order = 2);
    INSERT INTO public.launch_stages (name, sort_order, duration_days, details)
    SELECT 'Cohort 1 Live', 3, 28, E'First batch of customers are live with the new feature and we are ready to support them.\n\nCustomer facing training/pendo''s/help center articles complete.\n\nService Delivery and Support processes trained in and ready to execute.'
    WHERE NOT EXISTS (SELECT 1 FROM public.launch_stages WHERE sort_order = 3);
    INSERT INTO public.launch_stages (name, sort_order, duration_days, details)
    SELECT 'GA / Cohort 2 Live', 4, NULL, E'All customers are live with the new feature'
    WHERE NOT EXISTS (SELECT 1 FROM public.launch_stages WHERE sort_order = 4);
  END IF;
END $$;

DO $$
DECLARE
  st text;
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'launch_stages') THEN
    st := 'launch_stages';
  ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'release_stages') THEN
    st := 'release_stages';
  ELSE
    RAISE EXCEPTION '20260310000000_add_scope_to_launch_stages: expected public.launch_stages or public.release_stages';
  END IF;

  EXECUTE format(
    'ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS scope TEXT, ADD COLUMN IF NOT EXISTS level_durations JSONB, ADD COLUMN IF NOT EXISTS is_gate BOOLEAN DEFAULT FALSE',
    st
  );

  EXECUTE format('UPDATE public.%I SET scope = ''release_schedule'' WHERE scope IS NULL', st);

  EXECUTE format(
    'ALTER TABLE public.%I ALTER COLUMN scope SET DEFAULT ''release_schedule'', ALTER COLUMN scope SET NOT NULL',
    st
  );

  EXECUTE format(
    'CREATE UNIQUE INDEX IF NOT EXISTS launch_stages_scope_sort_order_key ON public.%I (scope, sort_order)',
    st
  );

  EXECUTE format(
    'UPDATE public.%I SET is_gate = TRUE WHERE scope = ''release_schedule'' AND name = ''GTM Access''',
    st
  );

  EXECUTE format($f$
    INSERT INTO public.%I (name, sort_order, duration_days, details, scope, level_durations, is_gate)
    SELECT 'UX Preview', 1, 63, 'Internal feedback and UX validation. Duration varies by Impact Level (Level 1: 8-10 wk, Level 2: 2-3 wk, Level 3: 1-2 wk).', 'ui_rollout',
      '{"1": {"min_days": 56, "max_days": 70}, "2": {"min_days": 14, "max_days": 21}, "3": {"min_days": 7, "max_days": 14}}'::jsonb,
      TRUE
    WHERE NOT EXISTS (SELECT 1 FROM public.%I WHERE scope = 'ui_rollout' AND sort_order = 1)
  $f$, st, st);

  EXECUTE format($f$
    INSERT INTO public.%I (name, sort_order, duration_days, details, scope, level_durations, is_gate)
    SELECT 'Internal Readiness', 2, 21, 'Product Education and internal enablement ready. Docs, training, and customer-facing materials in progress.', 'ui_rollout',
      '{"1": {"min_days": 28, "max_days": 42}, "2": {"min_days": 14, "max_days": 21}, "3": {"min_days": 7, "max_days": 14}}'::jsonb,
      FALSE
    WHERE NOT EXISTS (SELECT 1 FROM public.%I WHERE scope = 'ui_rollout' AND sort_order = 2)
  $f$, st, st);

  EXECUTE format($f$
    INSERT INTO public.%I (name, sort_order, duration_days, details, scope, level_durations, is_gate)
    SELECT 'CS Prep', 3, 14, 'Customer Success prep: Slack, FAQ, KB, support training. Customer email draft and outreach plan where required by level.', 'ui_rollout',
      '{"1": {"min_days": 21, "max_days": 28}, "2": {"min_days": 14, "max_days": 21}, "3": {"min_days": 7, "max_days": 14}}'::jsonb,
      TRUE
    WHERE NOT EXISTS (SELECT 1 FROM public.%I WHERE scope = 'ui_rollout' AND sort_order = 3)
  $f$, st, st);

  EXECUTE format($f$
    INSERT INTO public.%I (name, sort_order, duration_days, details, scope, level_durations, is_gate)
    SELECT 'Cohort 1', 4, 28, 'First cohort of customers live. Customer-facing training, Pendo, help center complete. Support ready.', 'ui_rollout',
      '{"1": {"min_days": 28, "max_days": 42}, "2": {"min_days": 21, "max_days": 28}, "3": {"min_days": 14, "max_days": 21}}'::jsonb,
      FALSE
    WHERE NOT EXISTS (SELECT 1 FROM public.%I WHERE scope = 'ui_rollout' AND sort_order = 4)
  $f$, st, st);

  EXECUTE format($f$
    INSERT INTO public.%I (name, sort_order, duration_days, details, scope, level_durations, is_gate)
    SELECT 'Cohort 2 / GA', 5, NULL, 'All customers live with the UI change.', 'ui_rollout', NULL, FALSE
    WHERE NOT EXISTS (SELECT 1 FROM public.%I WHERE scope = 'ui_rollout' AND sort_order = 5)
  $f$, st, st);
END $$;
